net use h: /d
net use o: /d
net use p: /d
net use t: /d
net use z: /d
net use h: \\file1\students\%username%
net use o: \\opetus1\%username%\public_html
net use p: \\file1\programs
net use t: \\file2\common\temporary
net use z: \\file2\common\permanent 